[package]
authors = ["Achim Schneider <achim@parity.io>"]
edition = "2021"
name = "test-host-nb-helper"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]